spring.application.name=request
server.port=8080

spring.datasource.url=jdbc:postgresql://ep-shiny-recipe-at3of3s9-pooler.c-9.us-east-1.aws.neon.tech:5432/todo?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_b6RcIFTtN1lg

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true